# Generated by Django 5.2.6 on 2025-11-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('red_social', models.CharField(blank=True, max_length=100, null=True)),
                ('imagenes_referencia', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('descripcion', models.TextField()),
                ('plataforma', models.CharField(default='pagina web', max_length=50)),
                ('fecha_necesita', models.DateField(blank=True, null=True)),
                ('token_seguimiento', models.CharField(blank=True, max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
        ),
    ]
