# Generated by Django 5.2.6 on 2025-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado')], default='Solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
    ]
