# Generated by Django 5.2.6 on 2025-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido_estado_pedido_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('En proceso', 'En proceso'), ('Realizada', 'Realizada'), ('Entregada', 'Entregada'), ('Finalizado', 'Finalizado'), ('Cancelada', 'Cancelada')], default='Solicitado', max_length=20),
        ),
    ]
