# Generated by Django 5.2.6 on 2025-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
    ]
