# Generated by Django 5.2.6 on 2025-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pedido_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='red_social',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('TikTok', 'TikTok'), ('Presencial', 'Presencial'), ('Sitio Web', 'Sitio Web')], default='Sitio Web', max_length=20),
        ),
    ]
