# Generated by Django 5.2.6 on 2025-12-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedido_red_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagenes',
        ),
    ]
