# Generated by Django 5.2.6 on 2025-12-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_destacado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_base',
            new_name='precio',
        ),
    ]
