# Generated by Django 5.2.6 on 2025-12-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_precio_base_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_base',
        ),
    ]
